### ISSUE TITLE
Crash caused by Psi, confirmed by Apotheosis Dev

### ISSUE THREAD

**Issue by ReeCodes** [Dudblockman/Psipherals#6]
https://pastebin.com/zPY9ea4s

**Comment by Dudblockman** [comment]
May I get some additional context? How was this crash reached?

**Comment by brisingraerowing** [comment]
This occurs on game initialization (common_setup event). Oddly, I didn't get the the first time I started my instance, but did the second time.

EDIT: The third run of the game didn't crash. This seems to be a threading related issue.

**Comment by brisingraerowing** [comment]
You need to use the event's `enqueueWork` method to run things in the event handler.

**Comment by Shadows-of-Fire** [comment]
This is caused by the lack of usage of a LazyValue<Ingredient> in your repair material here https://github.com/Dudblockman/Psipherals/blob/master/src/main/java/com/dudblockman/psipherals/util/libs/AdvPsimetalToolMaterial.java

You would need to make it match vanilla's usage as seen in `net.minecraft.item.ItemTier` by wrapping your Ingredient in a LazyValue<Ingredient> instead of direct usage.
